/*
 *  action type list
 */
export const FETCH_NEW_THEME = "FETCH_NEW_THEME"
export const FETCH_SETTING_STATUS = "FETCH_SETTING_STATUS"
export const FETCH_SIDE_BAR_IS_CLOSED = "FETCH_SIDE_BAR_IS_CLOSED"